word(hari, nn, [h,a,r,i], 2, filler).
word(hitam, nn, [h,i,t,a,m], 2, filler).
word(luka, nn, [l,u,k,a], 2, filler).
word(rindu, con, [r,i,n,d,u], 2, filler).
word(sepi, jj, [s,ax,p,i], 2, filler).
word(rasakan, vb, [r,a,s,a,k,a,n], 3, filler).
word(kamu, pr, [k,a,m,u], 2, filler).
word(terbang, vb, [t,ax,r,b,a,ng], 2, filler).
word(terdiam, nn, [t,ax,r,d,i,y,a,m], 3, filler).
word(sajak, con, [s,a,j,a,k], 2, filler).
word(suara, nn, [s,u,w,a,r,a], 3, filler).
word(kalbu, con, [k,a,l,b,u], 2, filler).
word(pahit, jj, [p,a,h,i,t], 2, filler).
word(tiba, vb, [t,i,b,a], 2, filler).
word(rembulan, con, [r,ax,m,b,u,l,a,n], 3, filler).
word(diam, vb, [d,i,y,a,m], 2, filler).
word(suka, vb, [s,u,k,a], 2, filler).
word(mentari, nn, [m,ax,n,t,a,r,i], 3, filler).
word(cinta, nn, [c,i,n,t,a], 2, filler).
word(bersama, in, [b,ax,r,s,a,m,a], 3, filler).
word(kehidupan, nn, [k,ax,h,i,d,u,p,a,n], 4, filler).
word(berat, jj, [b,ax,r,a,t], 2, filler).
word(melayang, vb, [m,ax,l,a,y,a,ng], 3, filler).
word(menunggu, vb, [m,ax,n,u,ng,g,u], 3, filler).
word(aku, pr, [a,k,u], 2, filler).
word(saja, rb, [s,a,j,a], 2, filler).
word(pergi, vb, [p,ax,r,g,i], 2, filler).
word(biru, nn, [b,i,r,u], 2, filler).
word(tersesat, con, [t,ax,r,s,ax,s,a,t], 3, filler).
word(engkau, con, [ax,ng,k,aw], 2, filler).
word(pilu, con, [p,i,l,u], 2, filler).
word(debu, nn, [d,ax,b,u], 2, filler).
word(mati, vb, [m,a,t,i], 2, filler).
word(sendiri, rb, [s,ax,n,d,i,r,i], 3, filler).
word(jiwa, nn, [j,i,w,a], 2, filler).
word(rumah, nn, [r,u,m,a,h], 2, filler).
word(matahari, nn, [m,a,t,a,h,a,r,i], 4, filler).
word(mimpi, nn, [m,i,m,p,i], 2, filler).
word(menghilang, vb, [m,ax,ng,h,i,l,a,ng], 3, filler).
word(sakit, jj, [s,a,k,i,t], 2, filler).
word(senja, nn, [s,ax,n,j,a], 2, filler).
word(bayang, nn, [b,a,y,a,n,g], 2, filler).
word(langit, nn, [l,a,ng,i,t], 2, filler).
word(kembali, vb, [k,ax,m,b,a,l,i], 3, filler).
word(angin, nn, [a,ng,i,n], 2, filler).
word(kau, pr, [k,aw], 1, filler).
word(lagu, nn, [l,a,g,u], 2, filler).
word(memandang, vb, [m,ax,m,a,n,d,a,ng], 3, filler).
word(kami, pr, [k,a,m,i], 2, filler).
word(duka, nn, [d,u,k,a], 2, filler).