:- multifile word/5.
word(departemen, nn, [d,ax,p,a,r,t,ax,m,e,n], 4, keyword).
word(tengah, nn, [t,ax,ng,a,h], 2, keyword).
word(jadi, vb, [j,a,d,i], 2, keyword).
word(sinetron, con, [s,i,n,e,t,r,o,n], 3, keyword).
word(program, nn, [p,r,o,g,r,a,m], 2, keyword).
word(bumn, con, [b,e,u,e,m,e,n], 4, keyword).
word(pemerintah, nn, [p,ax,m,ax,r,i,n,t,a,h], 4, keyword).
word(tetap, jj, [t,ax,t,a,p], 2, keyword).
word(ekonomi, nn, [e,k,o,n,o,m,i], 4, keyword).
word(yg, nn, [y,e,g,e], 2, keyword).
word(pemberantasan, nn, [p,ax,m,b,ax,r,a,n,t,a,s,a,n], 5, keyword).
word(dzikir, con, [z,i,k,i,r], 2, keyword).
word(menit, nn, [m,ax,n,i,t], 2, keyword).
word(eksklusif, jj, [e,k,s,k,l,u,s,i,f], 3, keyword).
word(a, nn, [a], 1, keyword).
word(orde, nn, [o,r,d,ax], 2, keyword).
word(menentukan, vb, [m,ax,n,ax,n,t,u,k,a,n], 4, keyword).
word(November, nn, [N,o,v,e,m,b,e,r], 3, keyword).
word(memiliki, vb, [m,ax,m,i,l,i,k,i], 4, keyword).
word(ratusan, cd, [r,a,t,u,s,a,n], 3, keyword).
word(i, nn, [i], 1, keyword).
word(perasaan, nn, [p,ax,r,a,s,a,a,n], 4, keyword).
word(didasarkan, vb, [d,i,d,a,s,a,r,k,a,n], 4, keyword).
word(era, nn, [e,r,a], 2, keyword).
word(berhubungan, vb, [b,ax,r,h,u,b,u,ng,a,n], 4, keyword).
word(blog, nn, [b,l,o,g], 1, keyword).
word(kasasi, con, [k,a,s,a,s,i], 3, keyword).
word(jpu, con, [j,e,p,e,u], 3, keyword).
word(berarti, vb, [b,ax,r,a,r,t,i], 3, keyword).
word(ahli, nn, [a,h,l,i], 2, keyword).
word(memutar, vb, [m,ax,m,u,t,a,r], 3, keyword).
word(teknis, jj, [t,e,k,n,i,s], 2, keyword).
word(hidup, nn, [h,i,d,u,p], 2, keyword).
word(korupsi, nn, [k,o,r,u,p,s,i], 3, keyword).
word(siswa, nn, [s,i,s,w,a], 2, keyword).
word(tv, nn, [t,i,f,i], 2, keyword).
word(yakin, vb, [y,a,k,i,n], 2, keyword).
word(sistem, nn, [s,i,s,t,ax,m], 2, keyword).
word(atas, in, [a,t,a,s], 2, keyword).
word(sang, oth, [s,a,ng], 1, keyword).
word(peningkatan, nn, [p,ax,n,i,ng,k,a,t,a,n], 4, keyword).
word(membeli, vb, [m,ax,m,b,ax,l,i], 3, keyword).
word(pesan, nn, [p,ax,s,a,n], 2, keyword).
word(sekedar, rb, [s,ax,k,ax,d,a,r], 3, keyword).
word(gereja, nn, [g,ax,r,e,j,a], 3, keyword).
word(rakyat, nn, [r,a,k,y,a,t], 2, keyword).
word(pasal, nn, [p,a,s,a,l], 2, keyword).
word(ton, nn, [t,o,n], 1, keyword).
word(laut, nn, [l,a,w,u,t], 2, keyword).
word(berat, jj, [b,ax,r,a,t], 2, keyword).
word(pakan, nn, [p,a,k,a,n], 2, keyword).
word(rekayasa, nn, [r,e,k,a,y,a,s,a], 4, keyword).
word(penyidik, nn, [p,ax,ny,i,d,i,k], 3, keyword).
word(allah, con, [a,w,l,o,h], 2, keyword).
word(jalan, nn, [j,a,l,a,n], 2, keyword).
word(hakim, nn, [h,a,k,i,m], 2, keyword).
word(pertobatan, con, [p,ax,r,t,o,b,a,t,a,n], 4, keyword).
word(dokter, nn, [d,o,k,t,ax,r], 2, keyword).
word(fm, con, [e,f,e,m], 2, keyword).
word(beratnya, nn, [b,ax,r,a,t,ny,a], 3, keyword).
word(cahayanya, nn, [c,a,h,a,y,a,ny,a], 4, keyword).
word(baru, jj, [b,a,r,u], 2, keyword).
word(sedia, con, [s,ax,d,i,y,a], 3, keyword).
word(bisnis, nn, [b,i,s,n,i,s], 2, keyword).
word(menjatuhkan, vb, [m,ax,n,j,a,t,u,h,k,a,n], 4, keyword).
word(porno, nn, [p,o,r,n,o], 2, keyword).
word(dikurangi, vb, [d,i,k,u,r,a,ng,i], 4, keyword).
word(terhormat, vb, [t,ax,r,h,o,r,m,a,t], 3, keyword).
word(sedini, jj, [s,ax,d,i,n,i], 3, keyword).
word(kemarin, rb, [k,ax,m,a,r,i,n], 3, keyword).
word(jenderal, nn, [j,e,n,d,ax,r,a,l], 3, keyword).
word(tags, con, [t,a,g,s], 1, keyword).
word(dijerat, con, [d,i,j,ax,r,a,t], 3, keyword).
word(film, nn, [f,i,l,ax,m], 2, keyword).
word(kehidupan, nn, [k,ax,h,i,d,u,p,a,n], 4, keyword).
word(protestan, nn, [p,r,o,t,e,s,t,a,n], 3, keyword).
word(operasi, nn, [o,p,ax,r,a,s,i], 4, keyword).
word(disebut, vb, [d,i,s,ax,b,u,t], 3, keyword).
word(tuanya, nn, [t,u,w,a,ny,a], 3, keyword).
word(penjuru, nn, [p,ax,n,j,u,r,u], 3, keyword).
word(ancaman, nn, [a,n,c,a,m,a,n], 3, keyword).
word(good, nn, [g,o,o,d], 2, keyword).
word(aja, con, [a,j,a], 2, keyword).
word(dilakukan, vb, [d,i,l,a,k,u,k,a,n], 4, keyword).
word(dihadiri, vb, [d,i,h,a,d,i,r,i], 4, keyword).
word(kerja, nn, [k,ax,r,j,a], 2, keyword).
word(siap, nn, [s,i,y,a,p], 2, keyword).
word(divonis, vb, [d,i,f,o,n,i,s], 3, keyword).
word(saksi, nn, [s,a,k,s,i], 2, keyword).
word(sedih, jj, [s,ax,d,i,h], 2, keyword).
word(usual, nn, [u,s,u,a,l], 3, keyword).
word(amerika, nn, [a,m,e,r,i,k,a], 4, keyword).
word(usg, con, [u,s,g], 1, keyword).
word(musa, con, [m,u,s,a], 2, keyword).
word(parlemen, nn, [p,a,r,l,ax,m,e,n], 3, keyword).
word(perkantoran, nn, [p,ax,r,k,a,n,t,o,r,a,n], 4, keyword).
word(pagi, nn, [p,a,g,i], 2, keyword).
word(sebisa, con, [s,ax,b,i,s,a], 3, keyword).
word(pembangunan, nn, [p,ax,m,b,a,ng,u,n,a,n], 4, keyword).
word(bedah, nn, [b,ax,d,a,h], 2, keyword).
word(kebaktian, con, [k,ax,b,a,k,t,i,y,a,n], 4, keyword).
word(kesalahan, nn, [k,ax,s,a,l,a,h,a,n], 4, keyword).
word(menghadapi, vb, [m,ax,ng,h,a,d,a,p,i], 4, keyword).
word(malam, nn, [m,a,l,a,m], 2, keyword).
word(mendapatkan, vb, [m,ax,n,d,a,p,a,t,k,a,n], 4, keyword).
word(penerbangan, nn, [p,ax,n,ax,r,b,a,ng,a,n], 4, keyword).
word(milyar, cd, [m,i,l,y,a,r], 2, keyword).
word(pendidikan, nn, [p,ax,n,d,i,d,i,k,a,n], 4, keyword).
word(sepupunya, con, [s,ax,p,u,p,u,ny,a], 4, keyword).
word(uang, nn, [u,w,a,ng], 2, keyword).
word(berwenang, vb, [b,ax,r,w,ax,n,a,ng], 3, keyword).
word(dunia, nn, [d,u,n,i,y,a], 3, keyword).
word(luar, nn, [l,u,w,a,r], 2, keyword).
word(berumur, vb, [b,ax,r,u,m,u,r], 3, keyword).
word(pertambangan, nn, [p,ax,r,t,a,m,b,a,ng,a,n], 4, keyword).
word(pejabat, nn, [p,ax,j,a,b,a,t], 3, keyword).
word(teknologi, nn, [t,e,k,n,o,l,o,g,i], 4, keyword).
word(pukul, nn, [p,u,k,u,l], 2, keyword).
word(lembaga, nn, [l,ax,m,b,a,g,a], 3, keyword).
word(membantu, vb, [m,ax,m,b,a,n,t,u], 3, keyword).
word(kemanusiaan, nn, [k,ax,m,a,n,u,s,i,y,a,a,n], 6, keyword).
word(bertahan, vb, [b,ax,r,t,a,h,a,n], 3, keyword).
word(kesempatan, nn, [k,ax,s,ax,m,p,a,t,a,n], 4, keyword).
word(masyarakat, nn, [m,a,sy,a,r,a,k,a,t], 4, keyword).
word(terbesar, jj, [t,ax,r,b,ax,s,a,r], 3, keyword).
word(nuh, con, [n,u,h], 1, keyword).
word(dibangun, vb, [d,i,b,a,ng,u,n], 3, keyword).
word(isa, con, [i,s,a], 2, keyword).
word(radio, nn, [r,a,d,i,y,o], 3, keyword).
word(hotel, nn, [h,o,t,e,l], 2, keyword).
word(jaksa, nn, [j,a,k,s,a], 2, keyword).
word(kasus, nn, [k,a,s,u,s], 2, keyword).
word(iklan, nn, [i,k,l,a,n], 2, keyword).
word(sektor, nn, [s,e,k,t,o,r], 2, keyword).
word(umum, jj, [u,m,u,m], 2, keyword).
word(pencakar, nn, [p,ax,n,c,a,k,a,r], 3, keyword).
word(pemilu, nn, [p,ax,m,i,l,u], 3, keyword).
word(bentuk, nn, [b,ax,n,t,u,k], 2, keyword).
word(saham, nn, [s,a,h,a,m], 2, keyword).
word(dibaptis, con, [d,i,b,a,p,t,i,s], 3, keyword).
word(sesuai, jj, [s,ax,s,u,w,ay], 3, keyword).
word(negara, nn, [n,ax,g,a,r,a], 3, keyword).
word(berkata, vb, [b,ax,r,k,a,t,a], 3, keyword).
word(publik, nn, [p,u,b,l,i,k], 2, keyword).
word(turun, vb, [t,u,r,u,n], 2, keyword).
word(sanksi, nn, [s,a,ng,s,i], 2, keyword).
word(adam, con, [a,d,a,m], 2, keyword).
word(penjualan, nn, [p,ax,n,j,u,w,a,l,a,n], 4, keyword).
word(digunakan, vb, [d,i,g,u,n,a,k,a,n], 4, keyword).
word(akhirat, nn, [a,kh,i,r,a,t], 3, keyword).
word(si, oth, [s,i], 1, keyword).
word(mata, nn, [m,a,t,a], 2, keyword).
word(bus, nn, [b,u,s], 1, keyword).
word(majalah, nn, [m,a,j,a,l,a,h], 3, keyword).
word(aspirasi, nn, [a,s,p,i,r,a,s,i], 4, keyword).
word(dewasa, jj, [d,e,w,a,s,a], 3, keyword).
word(kampung, nn, [k,a,m,p,u,ng], 2, keyword).
word(usaha, nn, [u,s,a,h,a], 3, keyword).
word(kabinet, nn, [k,a,b,i,n,e,t], 3, keyword).
word(dijatuhkan, vb, [d,i,j,a,t,u,h,k,a,n], 4, keyword).
word(bersalah, vb, [b,ax,r,s,a,l,a,h], 3, keyword).
word(acara, nn, [a,c,a,r,a], 3, keyword).
word(panitia, nn, [p,a,n,i,t,i,y,a], 4, keyword).
word(tang, nn, [t,a,ng], 1, keyword).
word(berkaitan, vb, [b,ax,r,k,a,y,i,t,a,n], 4, keyword).
word(emailblogthis, con, [e,m,a,i,l,b,l,o,g,t,h,i,s], 5, keyword).
word(kereta, nn, [k,ax,r,e,t,a], 3, keyword).
word(melayani, vb, [m,ax,l,a,y,a,n,i], 4, keyword).
word(pandangan, nn, [p,a,n,d,a,ng,a,n], 3, keyword).
word(menerima, vb, [m,ax,n,ax,r,i,m,a], 4, keyword).
word(pakai, vb, [p,a,k,ay], 2, keyword).
word(rasi, con, [r,a,s,i], 2, keyword).
word(peraturan, nn, [p,ax,r,a,t,u,r,a,n], 4, keyword).
word(dikerjakan, vb, [d,i,k,ax,r,j,a,k,a,n], 4, keyword).
word(ditahan, vb, [d,i,t,a,h,a,n], 3, keyword).
word(saudari, nn, [s,aw,d,a,r,i], 3, keyword).
word(awal, nn, [a,w,a,l], 2, keyword).
word(pertanian, nn, [p,ax,r,t,a,n,i,y,a,n], 4, keyword).
word(koordinasi, nn, [k,o,o,r,d,i,n,a,s,i], 5, keyword).
word(muda, jj, [m,u,d,a], 2, keyword).
word(kader, nn, [k,a,d,ax,r], 2, keyword).
word(saji, nn, [s,a,j,i], 2, keyword).
word(nggak, nn, [ng,g,a,kk], 1, keyword).
word(tersangka, nn, [t,ax,r,s,a,ng,k,a], 3, keyword).
word(lahan, nn, [l,a,h,a,n], 2, keyword).
word(must, nn, [m,u,s,t], 1, keyword).
word(dibagi, vb, [d,i,b,a,g,i], 3, keyword).
word(perusahaan, nn, [p,ax,r,u,s,a,h,a,a,n], 5, keyword).
word(menteri, nn, [m,ax,n,t,r,i], 2, keyword).
word(dosa, nn, [d,o,s,a], 2, keyword).
word(toko, nn, [t,o,k,o], 2, keyword).
word(darah, nn, [d,a,r,a,h], 2, keyword).
word(investasi, nn, [i,n,f,e,s,t,a,s,i], 4, keyword).
word(tower, con, [t,o,w,e,r], 2, keyword).
word(dibandingkan, vb, [d,i,b,a,n,d,i,ng,k,a,n], 4, keyword).
word(nasi, nn, [n,a,s,i], 2, keyword).
word(beras, nn, [b,ax,r,a,s], 2, keyword).
word(breaking, con, [b,r,e,a,k,i,n,g], 3, keyword).
word(dibawa, vb, [d,i,b,a,w,a], 3, keyword).
word(menjalani, vb, [m,ax,n,j,a,l,a,n,i], 4, keyword).
word(omzet, con, [o,m,s,e,t], 2, keyword).
word(logged, con, [l,o,g,g,e,d], 2, keyword).
word(tempat, nn, [t,ax,m,p,a,t], 2, keyword).
word(rupiah, nn, [r,u,p,i,y,a,h], 3, keyword).
word(nyaman, jj, [ny,a,m,a,n], 2, keyword).
word(lantai, nn, [l,a,n,t,ay], 2, keyword).
word(dipandang, vb, [d,i,p,a,n,d,a,ng], 3, keyword).
word(komunikasi, nn, [k,o,m,u,n,i,k,a,s,i], 5, keyword).
word(pegawai, nn, [p,ax,g,a,w,ay], 3, keyword).
word(vonis, nn, [f,o,n,i,s], 2, keyword).
word(dijebloskan, vb, [d,i,j,ax,b,l,o,s,k,a,n], 4, keyword).
word(hard, nn, [h,a,r,d], 1, keyword).
word(jam, nn, [j,a,m], 1, keyword).
word(rasa, nn, [r,a,s,a], 2, keyword).
word(setimpal, con, [s,ax,t,i,m,p,a,l], 3, keyword).
word(demokrat, nn, [d,e,m,o,k,r,a,t], 3, keyword).
word(surabaya, con, [s,u,r,a,b,a,y,a], 4, keyword).
word(pks, con, [p,e,k,a,e,s], 3, keyword).
word(langit, nn, [l,a,ng,i,t], 2, keyword).
word(sarjana, nn, [s,a,r,j,a,n,a], 3, keyword).
word(sekretaris, nn, [s,ax,k,r,ax,t,a,r,i,s], 4, keyword).
word(diketuai, vb, [d,i,k,ax,t,u,w,a,y,i], 5, keyword).
word(hutan, nn, [h,u,t,a,n], 2, keyword).
word(perbedaan, nn, [p,ax,r,b,e,d,a,a,n], 4, keyword).
word(penciuman, nn, [p,ax,n,c,i,y,u,m,a,n], 4, keyword).
word(terintegrasi, vb, [t,ax,r,i,n,t,ax,g,r,a,s,i], 5, keyword).
word(wtc, con, [w,e,t,e,c,e], 3, keyword).
word(leave, con, [l,e,a,v,e], 3, keyword).
word(situasi, nn, [s,i,t,u,w,a,s,i], 4, keyword).
word(persidangan, nn, [p,ax,r,s,i,d,a,ng,a,n], 4, keyword).
word(perdana, nn, [p,ax,r,d,a,n,a], 3, keyword).
word(produksi, nn, [p,r,o,d,u,k,s,i], 3, keyword).
word(cara, nn, [c,a,r,a], 2, keyword).
word(gempa, nn, [g,ax,m,p,a], 2, keyword).
word(bekerja, vb, [b,ax,k,ax,r,j,a], 3, keyword).
word(ya, oth, [y,a], 1, keyword).
word(berusia, vb, [b,ax,r,u,s,i,y,a], 4, keyword).
word(kuhp, con, [k,a,u,h,a,p,e], 4, keyword).
word(sendok, nn, [s,e,n,d,o,k], 2, keyword).
word(nak, con, [n,a,kk], 1, keyword).
word(tahanan, nn, [t,a,h,a,n,a,n], 3, keyword).
word(terjual, vb, [t,ax,r,j,u,w,a,l], 3, keyword).
word(dibekuk, con, [d,i,b,ax,k,u,k], 3, keyword).
word(kirimkan, nn, [k,i,r,i,m,k,a,n], 3, keyword).
word(mencapai, vb, [m,ax,n,c,a,p,ay], 3, keyword).
word(menangis, vb, [m,ax,n,a,ng,i,s], 3, keyword).
word(pengelolaan, nn, [p,ax,ng,ax,l,o,l,a,a,n], 5, keyword).
word(badan, nn, [b,a,d,a,n], 2, keyword).
word(diancam, vb, [d,i,a,n,c,a,m], 3, keyword).
word(guru, nn, [g,u,r,u], 2, keyword).
word(standar, nn, [s,t,a,n,d,a,r], 2, keyword).
word(sholat, vb, [s,h,o,l,a,t], 2, keyword).
word(juni, nn, [j,u,n,i], 2, keyword).
word(alat, nn, [a,l,a,t], 2, keyword).
word(wakil, nn, [w,a,k,i,l], 2, keyword).
word(instansi, nn, [i,n,s,t,a,n,s,i], 3, keyword).
word(agung, jj, [a,g,u,ng], 2, keyword).
word(dasar, nn, [d,a,s,a,r], 2, keyword).
word(sekolah, nn, [s,ax,k,o,l,a,h], 3, keyword).
word(ditetapkan, vb, [d,i,t,ax,t,a,p,k,a,n], 4, keyword).
word(bandung, con, [b,a,n,d,u,ng], 2, keyword).
word(keluar, vb, [k,ax,l,u,w,a,r], 3, keyword).
word(kembali, vb, [k,ax,m,b,a,l,i], 3, keyword).
word(penglihatan, nn, [p,ax,ng,l,i,h,a,t,a,n], 4, keyword).
word(dua, cd, [d,u,w,a], 2, keyword).
word(menuju, vb, [m,ax,n,u,j,u], 3, keyword).
word(seiman, con, [s,e,i,m,a,n], 3, keyword).
word(budaya, nn, [b,u,d,a,y,a], 3, keyword).
word(kamar, nn, [k,a,m,a,r], 2, keyword).
word(golkar, con, [g,o,l,k,a,r], 2, keyword).
word(berdasarkan, vb, [b,ax,r,d,a,s,a,r,k,a,n], 4, keyword).
word(berkisar, vb, [b,ax,r,k,i,s,a,r], 3, keyword).
word(komisinya, con, [k,o,m,i,s,i,ny,a], 4, keyword).
word(dihubungi, nn, [d,i,h,u,b,u,ng,i], 4, keyword).
word(hukuman, nn, [h,u,k,u,m,a,n], 3, keyword).
word(eiffel, con, [ey,f,ax,l], 2, keyword).
word(alasan, nn, [a,l,a,s,a,n], 3, keyword).
word(umumnya, nn, [u,m,u,m,ny,a], 3, keyword).
word(perbelanjaan, nn, [p,ax,r,b,ax,l,a,n,j,a,a,n], 5, keyword).
word(panen, nn, [p,a,n,e,n], 2, keyword).
word(politik, nn, [p,o,l,i,t,i,k], 3, keyword).
word(ikut, vb, [i,k,u,t], 2, keyword).
word(penyiar, nn, [p,ax,ny,i,y,a,r], 3, keyword).
word(tawar, jj, [t,a,w,a,r], 2, keyword).
word(surau, con, [s,u,r,aw], 2, keyword).
word(nilai, nn, [n,i,l,ay], 2, keyword).
word(koalisi, nn, [k,o,w,a,l,i,s,i], 4, keyword).
word(dolar, nn, [d,o,l,a,r], 2, keyword).
word(keenam, cd, [k,ax,ax,n,a,m], 3, keyword).
word(aturan, nn, [a,t,u,r,a,n], 3, keyword).
word(berkunjung, vb, [b,ax,r,k,u,n,j,u,ng], 3, keyword).
word(mengajar, vb, [m,ax,ng,a,j,a,r], 3, keyword).
word(menempati, vb, [m,ax,n,ax,m,p,a,t,i], 4, keyword).
word(tanggal, nn, [t,a,ng,g,a,l], 2, keyword).
word(nepotisme, con, [n,e,p,o,t,i,s,m,ax], 4, keyword).
word(lahir, nn, [l,a,h,i,r], 2, keyword).
word(presiden, nn, [p,r,e,s,i,d,e,n], 3, keyword).
word(terkecil, nn, [t,ax,r,k,ax,c,i,l], 3, keyword).
word(running, nn, [r,u,n,n,i,n,g], 2, keyword).
word(kristen, con, [k,r,i,s,t,ax,n], 2, keyword).
word(negeri, nn, [n,ax,g,ax,r,i], 3, keyword).
word(menderita, vb, [m,ax,n,d,ax,r,i,t,a], 4, keyword).
word(pelaksanaan, nn, [p,ax,l,a,k,s,a,n,a,a,n], 5, keyword).
word(warga, nn, [w,a,r,g,a], 2, keyword).
word(halnya, nn, [h,a,l,ny,a], 2, keyword).
word(menjadi, vb, [m,ax,n,j,a,d,i], 3, keyword).
word(said, nn, [s,a,i,t], 2, keyword).
word(puluh, cd, [p,u,l,u,h], 2, keyword).
word(dianggap, vb, [d,i,a,ng,g,a,p], 3, keyword).
word(siaran, nn, [s,i,y,a,r,a,n], 3, keyword).
word(keputusan, nn, [k,ax,p,u,t,u,s,a,n], 4, keyword).
word(untuk, in, [u,n,t,u,k], 2, keyword).
word(fisik, nn, [f,i,s,i,k], 2, keyword).
word(komisi, nn, [k,o,m,i,s,i], 3, keyword).
word(menempatkan, vb, [m,ax,n,ax,m,p,a,t,k,a,n], 4, keyword).
word(panca, con, [p,a,n,c,a], 2, keyword).
word(informasi, nn, [i,n,f,o,r,m,a,s,i], 4, keyword).
word(juri, nn, [j,u,r,i], 2, keyword).
word(perekonomian, nn, [p,ax,r,e,k,o,n,o,m,i,y,a,n], 6, keyword).
word(ribu, cd, [r,i,b,u], 2, keyword).
word(berdosa, vb, [b,ax,r,d,o,s,a], 3, keyword).
word(miliar, cd, [m,i,l,i,y,a,r], 3, keyword).
word(membebaskan, vb, [m,ax,m,b,e,b,a,s,k,a,n], 4, keyword).
word(pintu, nn, [p,i,n,t,u], 2, keyword).
word(gelombang, nn, [g,ax,l,o,m,b,a,ng], 3, keyword).
word(belahan, nn, [b,ax,l,a,h,a,n], 3, keyword).
word(interaksi, nn, [i,n,t,ax,r,a,k,s,i], 4, keyword).
word(pelaku, nn, [p,ax,l,a,k,u], 3, keyword).
word(imam, nn, [i,m,a,m], 2, keyword).
word(masuk, vb, [m,a,s,u,k], 2, keyword).
word(tubuh, nn, [t,u,b,u,h], 2, keyword).
word(membangun, vb, [m,ax,m,b,a,ng,u,n], 3, keyword).
word(samping, nn, [s,a,m,p,i,ng], 2, keyword).
word(kondusif, jj, [k,o,n,d,u,s,i,f], 3, keyword).
word(meningkatkan, vb, [m,ax,n,i,ng,k,a,t,k,a,n], 4, keyword).
word(total, nn, [t,o,t,a,l], 2, keyword).
word(pelayanan, nn, [p,ax,l,a,y,a,n,a,n], 4, keyword).
word(gedung, nn, [g,ax,d,u,ng], 2, keyword).
word(anggota, nn, [a,ng,g,o,t,a], 3, keyword).
word(lingkungan, nn, [l,i,ng,k,u,ng,a,n], 3, keyword).
word(pidato, nn, [p,i,d,a,t,o], 3, keyword).
word(menjadikan, vb, [m,ax,n,j,a,d,i,k,a,n], 4, keyword).
word(baik, jj, [b,a,y,i,k], 2, keyword).
word(dipimpinnya, nn, [d,i,p,i,m,p,i,n,ny,a], 4, keyword).
word(muncul, vb, [m,u,n,c,u,l], 2, keyword).
word(bebas, jj, [b,e,b,a,s], 2, keyword).
word(lanjut, jj, [l,a,n,j,u,t], 2, keyword).
word(mesin, nn, [m,ax,s,i,n], 2, keyword).
word(baruku, con, [b,a,r,u,k,u], 3, keyword).
word(televisi, nn, [t,ax,l,ax,f,i,s,i], 4, keyword).
word(gubernur, nn, [g,u,b,ax,r,n,u,r], 3, keyword).
word(meter, nn, [m,e,t,ax,r], 2, keyword).
word(dasarnya, nn, [d,a,s,a,r,ny,a], 3, keyword).
word(lidah, nn, [l,i,d,a,h], 2, keyword).
word(terlambat, jj, [t,ax,r,l,a,m,b,a,t], 3, keyword).
word(praduga, con, [p,r,a,d,u,g,a], 3, keyword).
word(putusan, nn, [p,u,t,u,s,a,n], 3, keyword).
word(pemeriksaan, nn, [p,ax,m,ax,r,i,k,s,a,a,n], 5, keyword).
word(diajukan, vb, [d,i,a,j,u,k,a,n], 4, keyword).
word(us, nn, [u,s], 1, keyword).
word(dibentuk, vb, [d,i,b,ax,n,t,u,k], 3, keyword).
word(b, nn, [b,e], 1, keyword).
word(gak, con, [g,a,kk], 1, keyword).
word(dugaan, nn, [d,u,g,a,a,n], 3, keyword).
word(triliun, cd, [t,r,i,l,i,y,u,n], 3, keyword).
word(tuhan, nn, [t,u,h,a,n], 2, keyword).
word(sore, nn, [s,o,r,e], 2, keyword).
word(pengadilan, nn, [p,ax,ng,a,d,i,l,a,n], 4, keyword).
word(rangka, nn, [r,a,ng,k,a], 2, keyword).
word(anak, nn, [a,n,a,k], 2, keyword).
word(tiga, cd, [t,i,g,a], 2, keyword).
word(masa, nn, [m,a,s,a], 2, keyword).
word(iii, con, [i,i,i], 3, keyword).
word(merta, nn, [m,ax,r,t,a], 2, keyword).
word(berbeda, vb, [b,ax,r,b,e,d,a], 3, keyword).
word(menduduki, vb, [m,ax,n,d,u,d,u,k,i], 4, keyword).
word(rumah, nn, [r,u,m,a,h], 2, keyword).
word(dipilih, vb, [d,i,p,i,l,i,h], 3, keyword).
word(semaksimal, jj, [s,ax,m,a,k,s,i,m,a,l], 4, keyword).
word(cukup, jj, [c,u,k,u,p], 2, keyword).
word(bergerak, vb, [b,ax,r,g,ax,r,a,k], 3, keyword).
word(pondok, con, [p,o,n,d,o,k], 2, keyword).
word(studi, nn, [s,t,u,d,i], 2, keyword).
word(berpengaruh, vb, [b,ax,r,p,ax,ng,a,r,u,h], 4, keyword).
word(komentar, nn, [k,o,m,e,n,t,a,r], 3, keyword).
word(verbal, jj, [f,ax,r,b,a,l], 2, keyword).
word(gram, nn, [g,r,a,m], 1, keyword).
word(sembuh, vb, [s,ax,m,b,u,h], 2, keyword).
word(zaman, nn, [z,a,m,a,n], 2, keyword).
word(bidang, nn, [b,i,d,a,ng], 2, keyword).
word(as, nn, [a,e,s], 2, keyword).
word(sejumlah, cd, [s,ax,j,u,m,l,a,h], 3, keyword).
word(hukum, nn, [h,u,k,u,m], 2, keyword).
word(surat, nn, [s,u,r,a,t], 2, keyword).
word(kembar, jj, [k,ax,m,b,a,r], 2, keyword).
word(link, nn, [l,i,n,k], 1, keyword).
word(dikenal, vb, [d,i,k,ax,n,a,l], 3, keyword).
word(pancasila, con, [p,a,n,c,a,s,i,l,a], 4, keyword).
word(sidang, nn, [s,i,d,a,ng], 2, keyword).
word(cairan, nn, [c,a,y,i,r,a,n], 3, keyword).
word(ali, con, [a,l,i], 2, keyword).
word(berita, nn, [b,ax,r,i,t,a], 3, keyword).
word(soeharto, con, [s,o,e,h,a,r,t,o], 4, keyword).
word(pengaruh, nn, [p,ax,ng,a,r,u,h], 3, keyword).
word(diet, nn, [d,i,y,e,t], 2, keyword).
word(pesawat, nn, [p,ax,s,a,w,a,t], 3, keyword).
word(minggu, nn, [m,i,ng,g,u], 2, keyword).
word(berikut, vb, [b,ax,r,i,k,u,t], 3, keyword).
word(madrasah, nn, [m,a,d,r,a,s,a,h], 3, keyword).
word(eselon, nn, [e,s,ax,l,o,n], 3, keyword).
word(pidana, nn, [p,i,d,a,n,a], 3, keyword).
word(tinggi, jj, [t,i,ng,g,i], 2, keyword).
word(menetapkan, vb, [m,ax,n,ax,t,a,p,k,a,n], 4, keyword).
word(mega, nn, [m,e,g,a], 2, keyword).
word(bertanya, vb, [b,ax,r,t,a,ny,a], 3, keyword).
word(tahu, vb, [t,a,w,u], 2, keyword).
word(h, con, [h,a], 1, keyword).
word(proyek, nn, [p,r,o,y,e,k], 2, keyword).
word(indonesia, nn, [i,n,d,o,n,e,s,i,y,a], 5, keyword).
word(kaisar, nn, [k,ay,s,a,r], 2, keyword).
word(manajer, nn, [m,e,n,e,j,ax,r], 3, keyword).
word(diberikan, vb, [d,i,b,ax,r,i,k,a,n], 4, keyword).
word(sipil, jj, [s,i,p,i,l], 2, keyword).
word(penumpang, nn, [p,ax,n,u,m,p,a,ng], 3, keyword).
word(facebook, con, [f,a,c,e,b,o,o,k], 4, keyword).
word(dpr, con, [d,e,p,e,e,r], 3, keyword).
word(paripurna, jj, [p,a,r,i,p,u,r,n,a], 4, keyword).
word(hasil, nn, [h,a,s,i,l], 2, keyword).
word(diposkan, vb, [d,i,p,o,s,k,a,n], 3, keyword).
word(berlangsung, vb, [b,ax,r,l,a,ng,s,u,ng], 3, keyword).
word(nabi, con, [n,a,b,i], 2, keyword).
word(abad, nn, [a,b,a,t], 2, keyword).
word(planet, nn, [p,l,a,n,e,t], 2, keyword).
word(matahari, nn, [m,a,t,a,h,a,r,i], 4, keyword).
word(pembelajaran, nn, [p,ax,m,b,ax,l,a,j,a,r,a,n], 5, keyword).
word(normal, jj, [n,o,r,m,a,l], 2, keyword).
word(tunai, vb, [t,u,n,ay], 2, keyword).
word(utara, nn, [u,t,a,r,a], 3, keyword).
word(sebentar, nn, [s,ax,b,ax,n,t,a,r], 3, keyword).
word(kristus, con, [k,r,i,s,t,u,s], 2, keyword).
word(dosis, nn, [d,o,s,i,s], 2, keyword).
word(usia, nn, [u,s,i,y,a], 3, keyword).
word(dilihat, vb, [d,i,l,i,h,a,t], 3, keyword).
word(demokrasi, nn, [d,e,m,o,k,r,a,s,i], 4, keyword).
word(rp, con, [e,r,p,e], 2, keyword).
word(pergi, vb, [p,ax,r,g,i], 2, keyword).
word(tamu, nn, [t,a,m,u], 2, keyword).
word(dipidana, con, [d,i,p,i,d,a,n,a], 4, keyword).
word(kesejahteraan, nn, [k,ax,s,ax,j,a,h,t,ax,r,a,a,n], 6, keyword).
word(satu, cd, [s,a,t,u], 2, keyword).
word(tanah, nn, [t,a,n,a,h], 2, keyword).
word(yesus, con, [y,e,s,u,s], 2, keyword).
word(century, nn, [s,e,n,t,u,r,i], 3, keyword).
word(putar, nn, [p,u,t,a,r], 2, keyword).
word(tetangga, nn, [t,ax,t,a,ng,g,a], 3, keyword).
word(berfungsi, vb, [b,ax,r,f,u,ng,s,i], 3, keyword).
word(komisaris, nn, [k,o,m,i,s,a,r,i,s], 4, keyword).
word(tanda, nn, [t,a,n,d,a], 2, keyword).
word(penghargaan, nn, [p,ax,ng,h,a,r,g,a,a,n], 4, keyword).
word(tindak, nn, [t,i,n,d,a,k], 2, keyword).
word(senilai, vb, [s,ax,n,i,l,ay], 3, keyword).
word(sosial, jj, [s,o,s,i,y,a,l], 3, keyword).
word(gayus, con, [g,a,y,u,s], 2, keyword).
word(mendekam, vb, [m,ax,n,d,ax,k,a,m], 3, keyword).
word(sd, con, [e,s,d,e], 2, keyword).
word(melebihi, vb, [m,ax,l,ax,b,i,h,i], 4, keyword).
word(gading, nn, [g,a,d,i,ng], 2, keyword).
word(sebesar, jj, [s,ax,b,ax,s,a,r], 3, keyword).
word(kesalahannya, nn, [k,ax,s,a,l,a,h,a,n,ny,a], 5, keyword).
word(dimulai, vb, [d,i,m,u,l,ay], 3, keyword).
word(dana, nn, [d,a,n,a], 2, keyword).
word(mantan, jj, [m,a,n,t,a,n], 2, keyword).
word(terkait, vb, [t,ax,r,k,a,y,i,t], 3, keyword).
word(pamen, con, [p,a,m,e,n], 2, keyword).
word(keadaan, nn, [k,ax,a,d,a,a,n], 4, keyword).
word(menekan, vb, [m,ax,n,ax,k,a,n], 3, keyword).
word(industri, nn, [i,n,d,u,s,t,r,i], 3, keyword).
word(jakarta, con, [j,a,k,a,r,t,a], 3, keyword).
word(polisi, nn, [p,o,l,i,s,i], 3, keyword).
word(selatan, nn, [s,ax,l,a,t,a,n], 3, keyword).
word(bawah, nn, [b,a,w,a,h], 2, keyword).
word(memberikan, vb, [m,ax,m,b,ax,r,i,k,a,n], 4, keyword).
word(pimpinan, nn, [p,i,m,p,i,n,a,n], 3, keyword).
word(value, nn, [v,a,l,u,e], 3, keyword).
word(persalinan, nn, [p,ax,r,s,a,l,i,n,a,n], 4, keyword).
word(pemerintahan, nn, [p,ax,m,ax,r,i,n,t,a,h,a,n], 5, keyword).
word(daerah, nn, [d,a,e,r,a,h], 3, keyword).
word(berikan, vb, [b,ax,r,i,k,a,n], 3, keyword).
word(mulut, nn, [m,u,l,u,t], 2, keyword).
word(dprd, con, [d,e,p,e,e,r,d,e], 4, keyword).
word(kota, nn, [k,o,t,a], 2, keyword).
word(mati, vb, [m,a,t,i], 2, keyword).
word(media, nn, [m,e,d,i,y,a], 3, keyword).
word(obat, nn, [o,b,a,t], 2, keyword).
word(barang, nn, [b,a,r,a,ng], 2, keyword).
word(ditangkap, vb, [d,i,t,a,ng,k,a,p], 3, keyword).
word(korban, nn, [k,o,r,b,a,n], 2, keyword).
word(terapi, nn, [t,ax,r,a,p,i], 3, keyword).
word(terminal, jj, [t,ax,r,m,i,n,a,l], 3, keyword).
word(jabatan, nn, [j,a,b,a,t,a,n], 3, keyword).
word(rajam, con, [r,a,j,a,m], 2, keyword).
word(kandung, nn, [k,a,n,d,u,ng], 2, keyword).
word(tidur, vb, [t,i,d,u,r], 2, keyword).
word(enam, cd, [ax,n,a,m], 2, keyword).
word(memutus, vb, [m,ax,m,u,t,u,s], 3, keyword).
word(tergantung, vb, [t,ax,r,g,a,n,t,u,ng], 3, keyword).
word(harga, nn, [h,a,r,g,a], 2, keyword).
word(pra, nn, [p,r,a], 1, keyword).
word(maya, nn, [m,a,y,a], 2, keyword).
word(kpk, con, [k,a,p,e,k,a], 3, keyword).
word(administrasi, nn, [a,t,m,i,n,i,s,t,r,a,s,i], 5, keyword).
word(santri, nn, [s,a,n,t,r,i], 2, keyword).
word(perasa, nn, [p,ax,r,a,s,a], 3, keyword).
word(mw, con, [e,m,w,e], 2, keyword).
word(salah, jj, [s,a,l,a,h], 2, keyword).
word(pt, con, [p,e,t,e], 2, keyword).
word(posisi, nn, [p,o,s,i,s,i], 3, keyword).
word(comment, nn, [c,o,m,m,e,n,t], 2, keyword).
word(sekian, nn, [s,ax,k,i,y,a,n], 3, keyword).
word(suap, nn, [s,u,w,a,p], 2, keyword).
word(datang, vb, [d,a,t,a,ng], 2, keyword).
word(gembala, nn, [g,ax,m,b,a,l,a], 3, keyword).
word(merasa, vb, [m,ax,r,a,s,a], 3, keyword).
word(belajar, vb, [b,ax,l,a,j,a,r], 3, keyword).
word(sisi, nn, [s,i,s,i], 2, keyword).
word(berbagi, vb, [b,ax,r,b,a,g,i], 3, keyword).
word(makan, vb, [m,a,k,a,n], 2, keyword).
word(utama, jj, [u,t,a,m,a], 3, keyword).
word(at, nn, [a,t], 1, keyword).
word(sikap, nn, [s,i,k,a,p], 2, keyword).
word(sanak, con, [s,a,n,a,k], 2, keyword).
word(teman, nn, [t,ax,m,a,n], 2, keyword).
word(penyumbang, nn, [p,ax,ny,u,m,b,a,ng], 3, keyword).
word(pengasuh, nn, [p,ax,ng,a,s,u,h], 3, keyword).
word(stasiun, nn, [s,t,a,s,i,y,u,n], 3, keyword).
word(kh, con, [k,h], 0, keyword).
word(angkutan, nn, [a,ng,k,u,t,a,n], 3, keyword).
word(terima, vb, [t,ax,r,i,m,a], 3, keyword).
word(tawaran, nn, [t,a,w,a,r,a,n], 3, keyword).
word(mobil, nn, [m,o,b,i,l], 2, keyword).
word(langsung, jj, [l,a,ng,s,u,ng], 2, keyword).
word(hadiah, nn, [h,a,d,i,y,a,h], 3, keyword).
word(logging, con, [l,o,g,g,i,n,g], 2, keyword).
word(siang, nn, [s,i,y,a,ng], 2, keyword).
word(pancung, con, [p,a,n,c,u,n,g], 2, keyword).
word(jutaan, cd, [j,u,t,a,a,n], 3, keyword).
word(pindah, vb, [p,i,n,d,a,h], 2, keyword).
word(dengar, vb, [d,ax,ng,a,r], 2, keyword).
word(mulutnya, nn, [m,u,l,u,t,ny,a], 3, keyword).
word(visual, jj, [f,i,s,u,w,a,l], 3, keyword).
word(jawab, nn, [j,a,w,a,p], 2, keyword).
word(kekebalan, nn, [k,ax,k,ax,b,a,l,a,n], 4, keyword).
word(terang, jj, [t,ax,r,a,ng], 2, keyword).
word(pendengaran, nn, [p,ax,n,d,ax,ng,a,r,a,n], 4, keyword).
word(sejauh, jj, [s,ax,j,a,w,u,h], 3, keyword).
word(terdakwa, nn, [t,ax,r,d,a,k,w,a], 3, keyword).
word(c, nn, [c,e], 1, keyword).
word(akal, nn, [a,k,a,l], 2, keyword).
word(pengobatan, nn, [p,ax,ng,o,b,a,t,a,n], 4, keyword).
word(kapal, nn, [k,a,p,a,l], 2, keyword).
word(arah, nn, [a,r,a,h], 2, keyword).
word(kelompok, nn, [k,ax,l,o,m,p,o,k], 3, keyword).
word(jelata, jj, [j,ax,l,a,t,a], 3, keyword).
word(juta, nn, [j,u,t,a], 2, keyword).
word(permusyawaratan, con, [p,ax,r,m,u,sy,a,w,a,r,a,t,a,n], 6, keyword).
word(mulai, vb, [m,u,l,ay], 2, keyword).
word(berhasil, vb, [b,ax,r,h,a,s,i,l], 3, keyword).
word(ri, con, [e,r,i], 2, keyword).
word(katolik, con, [k,a,t,o,l,i,k], 3, keyword).
word(penjara, nn, [p,ax,n,j,a,r,a], 3, keyword).
word(kolusi, con, [k,o,l,u,s,i], 3, keyword).
word(disebabkan, vb, [d,i,s,ax,b,a,b,k,a,n], 4, keyword).
word(shalat, nn, [s,o,l,a,t], 2, keyword).
word(keluarga, nn, [k,ax,l,u,w,a,r,g,a], 4, keyword).
word(sedapat, jj, [s,ax,d,a,p,a,t], 3, keyword).
word(kegiatan, nn, [k,ax,g,i,y,a,t,a,n], 4, keyword).
word(ham, con, [h,a,m], 1, keyword).
word(ustad, con, [u,s,t,a,t], 2, keyword).
word(kenyataan, nn, [k,ax,ny,a,t,a,a,n], 4, keyword).
word(berjamaah, con, [b,ax,r,j,a,m,a,a,h], 4, keyword).
word(kepala, nn, [k,ax,p,a,l,a], 3, keyword).
word(taklim, con, [t,a,kk,l,i,m], 2, keyword).
word(pemilihan, nn, [p,ax,m,i,l,i,h,a,n], 4, keyword).
word(puluhan, cd, [p,u,l,u,h,a,n], 3, keyword).
word(menggunakan, vb, [m,ax,ng,g,u,n,a,k,a,n], 4, keyword).
word(denda, nn, [d,ax,n,d,a], 2, keyword).
word(kata, nn, [k,a,t,a], 2, keyword).
word(masjid, nn, [m,a,s,j,i,t], 2, keyword).
word(bangunan, nn, [b,a,ng,u,n,a,n], 3, keyword).
word(menjabat, vb, [m,ax,n,j,a,b,a,t], 3, keyword).
word(kekerasan, nn, [k,ax,k,ax,r,a,s,a,n], 4, keyword).
word(berasal, vb, [b,ax,r,a,s,a,l], 3, keyword).
word(sinar, nn, [s,i,n,a,r], 2, keyword).
word(peraga, con, [p,ax,r,a,g,a], 3, keyword).
word(hubungan, nn, [h,u,b,u,ng,a,n], 3, keyword).
word(organisasi, nn, [o,r,g,a,n,i,s,a,s,i], 5, keyword).
word(tombol, nn, [t,o,m,b,o,l], 2, keyword).
word(duduk, vb, [d,u,d,u,k], 2, keyword).
word(bandara, nn, [b,a,n,d,a,r,a], 3, keyword).
word(kurungan, nn, [k,u,r,u,ng,a,n], 3, keyword).
word(ketua, nn, [k,ax,t,u,w,a], 3, keyword).
word(on, nn, [o,n], 1, keyword).
word(tahun, nn, [t,a,h,u,n], 2, keyword).
word(diharapkan, vb, [d,i,h,a,r,a,p,k,a,n], 4, keyword).
word(dekrit, nn, [d,e,k,r,i,t], 2, keyword).
word(lambat, jj, [l,a,m,b,a,t], 2, keyword).
word(kedaulatan, nn, [k,ax,d,aw,l,a,t,a,n], 4, keyword).
word(kepentingan, nn, [k,ax,p,ax,n,t,i,ng,a,n], 4, keyword).
word(menangani, vb, [m,ax,n,a,ng,a,n,i], 4, keyword).
word(kanker, nn, [k,a,ng,k,ax,r], 2, keyword).
word(bernilai, vb, [b,ax,r,n,i,l,ay], 3, keyword).
word(pengetahuan, nn, [p,ax,ng,ax,t,a,h,u,w,a,n], 5, keyword).
word(partai, nn, [p,a,r,t,ay], 2, keyword).
word(ga, con, [g,a], 1, keyword).
word(direksi, nn, [d,i,r,e,k,s,i], 3, keyword).
word(besar, jj, [b,ax,s,a,r], 2, keyword).
word(mahkamah, nn, [m,a,h,k,a,m,a,h], 3, keyword).
word(menyeluruh, vb, [m,ax,ny,ax,l,u,r,u,h], 4, keyword).
word(tugas, nn, [t,u,g,a,s], 2, keyword).
word(imunisasi, con, [i,m,u,n,i,s,a,s,i], 5, keyword).
word(dipengaruhi, vb, [d,i,p,ax,ng,a,r,u,h,i], 5, keyword).
word(dinyatakan, vb, [d,i,ny,a,t,a,k,a,n], 4, keyword).
word(laboratorium, nn, [l,a,b,o,r,a,t,o,r,i,y,u,m], 6, keyword).
word(terbukti, vb, [t,ax,r,b,u,k,t,i], 3, keyword).
word(unit, nn, [u,n,i,t], 2, keyword).
word(perwakilan, nn, [p,ax,r,w,a,k,i,l,a,n], 4, keyword).
word(perkara, nn, [p,ax,r,k,a,r,a], 3, keyword).
word(mengetahui, vb, [m,ax,ng,ax,t,a,h,u,w,i], 5, keyword).
word(bts, con, [b,e,t,e,e,s], 3, keyword).
word(mengerjakan, vb, [m,ax,ng,ax,r,j,a,k,a,n], 4, keyword).
word(tua, jj, [t,u,w,a], 2, keyword).
word(added, nn, [a,d,d,e,d], 2, keyword).
word(pengajar, nn, [p,ax,ng,a,j,a,r], 3, keyword).
word(persen, nn, [p,ax,r,s,e,n], 2, keyword).
word(ruang, nn, [r,u,w,a,ng], 2, keyword).
word(rapat, nn, [r,a,p,a,t], 2, keyword).
word(memberantas, vb, [m,ax,m,b,ax,r,a,n,t,a,s], 4, keyword).
word(tali, nn, [t,a,l,i], 2, keyword).
word(modal, nn, [m,o,d,a,l], 2, keyword).
word(kriminal, jj, [k,r,i,m,i,n,a,l], 3, keyword).
word(ramadhan, con, [r,a,m,a,d,a,n], 3, keyword).
word(terjadi, vb, [t,ax,r,j,a,d,i], 3, keyword).
word(dewan, nn, [d,e,w,a,n], 2, keyword).
word(mengangkut, vb, [m,ax,ng,a,ng,k,u,t], 3, keyword).
word(melakukan, vb, [m,ax,l,a,k,u,k,a,n], 4, keyword).
word(jemaat, nn, [j,ax,m,a,a,t], 3, keyword).
word(kejahatan, nn, [k,ax,j,a,h,a,t,a,n], 4, keyword).
word(perjalanan, nn, [p,ax,r,j,a,l,a,n,a,n], 4, keyword).
word(naik, vb, [n,a,y,i,k], 2, keyword).
word(pendapatan, nn, [p,ax,n,d,a,p,a,t,a,n], 4, keyword).
word(menurunkan, vb, [m,ax,n,u,r,u,n,k,a,n], 4, keyword).
word(tol, nn, [t,o,l], 1, keyword).
word(pertanyaan, nn, [p,ax,r,t,a,ny,a,a,n], 4, keyword).
word(kalo, con, [k,a,l,o], 2, keyword).
word(pesantren, con, [p,ax,s,a,n,t,r,e,n], 3, keyword).
word(puasa, nn, [p,u,w,a,s,a], 3, keyword).
word(kehutanan, nn, [k,ax,h,u,t,a,n,a,n], 4, keyword).
word(bulan, nn, [b,u,l,a,n], 2, keyword).
word(jamaah, nn, [j,a,m,a,a,h], 3, keyword).
word(majelis, nn, [m,a,j,ax,l,i,s], 3, keyword).
word(selesai, vb, [s,ax,l,ax,s,ay], 3, keyword).
word(strategis, jj, [s,t,r,a,t,e,g,i,s], 3, keyword).
word(eksekutif, nn, [e,k,s,ax,k,u,t,i,f], 4, keyword).
word(penghasil, nn, [p,ax,ng,h,a,s,i,l], 3, keyword).
word(tim, nn, [t,i,m], 1, keyword).
word(February, nn, [F,e,b,r,u,a,r,y], 3, keyword).
word(pembunuhan, nn, [p,ax,m,b,u,n,u,h,a,n], 4, keyword).
word(menolak, vb, [m,ax,n,o,l,a,k], 3, keyword).
word(dijatuhi, vb, [d,i,j,a,t,u,h,i], 4, keyword).
word(perang, nn, [p,ax,r,a,ng], 2, keyword).
word(doang, con, [d,o,w,a,ng], 2, keyword).
word(dipimpin, vb, [d,i,p,i,m,p,i,n], 3, keyword).
word(menengah, vb, [m,ax,n,ax,ng,a,h], 3, keyword).
word(dijadikan, vb, [d,i,j,a,d,i,k,a,n], 4, keyword).
word(secara, in, [s,ax,c,a,r,a], 3, keyword).
word(berada, vb, [b,ax,r,a,d,a], 3, keyword).
word(diartikan, vb, [d,i,a,r,t,i,k,a,n], 4, keyword).
word(pendeta, nn, [p,ax,n,d,e,t,a], 3, keyword).
word(ratus, cd, [r,a,t,u,s], 2, keyword).
word(perkebunan, nn, [p,ax,r,k,ax,b,u,n,a,n], 4, keyword).
word(ii, nn, [i,i], 2, keyword).
word(penurunan, nn, [p,ax,n,u,r,u,n,a,n], 4, keyword).
word(larut, jj, [l,a,r,u,t], 2, keyword).
word(membayar, vb, [m,ax,m,b,a,y,a,r], 3, keyword).
word(perawatan, nn, [p,ax,r,a,w,a,t,a,n], 4, keyword).
word(asi, con, [a,s,i], 2, keyword).
word(meninggal, vb, [m,ax,n,i,ng,g,a,l], 3, keyword).
word(membedakan, vb, [m,ax,m,b,e,d,a,k,a,n], 4, keyword).
word(hari, nn, [h,a,r,i], 2, keyword).
word(turut, nn, [t,u,r,u,t], 2, keyword).
word(pasien, nn, [p,a,s,i,y,e,n], 3, keyword).
word(ibrahim, con, [i,b,r,a,h,i,m], 3, keyword).
word(kemoterapi, nn, [k,e,m,o,t,ax,r,a,p,i], 5, keyword).
word(perdata, nn, [p,ax,r,d,a,t,a], 3, keyword).
word(twitterberbagi, con, [t,w,i,t,t,e,r,b,e,r,b,a,g,i], 5, keyword).
word(kbri, con, [k,a,b,e,e,r,i], 4, keyword).
word(peradilan, nn, [p,ax,r,a,d,i,l,a,n], 4, keyword).
word(rt, con, [e,r,t,e], 2, keyword).
word(proses, nn, [p,r,o,s,e,s], 2, keyword).
word(ditemui, vb, [d,i,t,ax,m,u,w,i], 4, keyword).
word(makanan, nn, [m,a,k,a,n,a,n], 3, keyword).
word(kredit, nn, [k,r,e,d,i,t], 2, keyword).
word(reformasi, nn, [r,e,f,o,r,m,a,s,i], 4, keyword).
word(birokrasi, nn, [b,i,r,o,k,r,a,s,i], 4, keyword).
word(kantor, nn, [k,a,n,t,o,r], 2, keyword).
word(kondisi, nn, [k,o,n,d,i,s,i], 3, keyword).
word(perikanan, nn, [p,ax,r,i,k,a,n,a,n], 4, keyword).
word(bahasa, nn, [b,a,h,a,s,a], 3, keyword).
